name: StatsTop
version: '1.2'
main: pl.statstop.StatsPlugin
api-version: '1.21'
author: StatsTop
description: Profesjonalny system statystyk killi graczy i zabójstw mobów z topką.

commands:
  statstop:
    description: Administracja pluginem StatsTop.
    usage: /statstop <reload|set|add|reset|show> [gracz] [wartosc]
    permission: statstop.admin
  topkills:
    description: Otwiera topliste graczy wedlug killi.
    usage: /topkills [player|mob] [strona]
    permission: statstop.top

permissions:
  statstop.admin:
    description: Dostep do administracji pluginem.
    default: op
  statstop.top:
    description: Dostep do toplisty.
    default: true
  statstop.top.chat:
    description: Pozwala na ogladanie topki w chatcie zamiast GUI.
    default: true